org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=34
org.gradle.parallel=true
org.gradle.caching=true

# Set to `true` if you haven't pulled the FCEUmm submodule yet and just want
# the UI to compile. Real gameplay needs the real core (set to `false`).
useStubCore=false

# Proxy settings
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
systemProp.http.nonProxyHosts=localhost|127.0.0.1|.svc|.cluster.local
