package com.nesstation.app.core.storage

/**
 * 街机游戏中文标题映射器
 *
 * FBNeo/MAME 街机 ROM 的 zip 文件名就是驱动名（driver name），
 * 例如 "kof97.zip"、"mvc.zip"、"sf2ce.zip"。这些名字对用户不友好。
 *
 * 本映射器收录了 600+ 款常见街机游戏的驱动名 → 中文名对应关系，
 * 涵盖：
 *   - CPS1/CPS2/CPS3（街头霸王、漫画英雄 vs Capcom、战国之刃 等）
 *   - NeoGeo（拳皇、合金弹头、侍魂、月华之剑士、恶狼传奇 等）
 *   - PGM（三国战纪、西游释厄传、形意拳、神剑伏魔录 等）
 *   - 经典街机（吃豆人、大蜜蜂、雪人兄弟、泡泡龙、雷电 等）
 *   - IGS 鼎盛时期作品
 *   - 部分经典 80 年代至 2000 年代街机
 *
 * 命名规则：
 *   1) 优先采用中国大陆玩家最熟悉的译名（如 KOF → 拳皇、Metal Slug → 合金弹头）
 *   2) 同时存在多代作品时，标题包含数字（如 拳皇97、合金弹头3）
 *   3) 修订版/合集版在末尾加副标题（如 街头霸王2'/冠军版）
 *
 * 调用入口：
 *   val title = ArcadeTitleMapper.lookup(driverName) ?: driverName
 */
object ArcadeTitleMapper {

    /**
     * 完整驱动名 → 中文名映射表。
     *
     * 注意：键全部小写，便于不区分大小写查找。
     */
    private val DRIVER_TO_CN: Map<String, String> = mapOf(
        // ========== SNK 拳皇系列 (King of Fighters) ==========
        "kof94" to "拳皇94",
        "kof95" to "拳皇95",
        "kof96" to "拳皇96",
        "kof97" to "拳皇97",
        "kof98" to "拳皇98 - 梦之终结未圆满",
        "kof98h" to "拳皇98 - 梦之终结未圆满",
        "kof98k" to "拳皇98 - 梦之终结未圆满",
        "kof99" to "拳皇99 - 千年之战",
        "kof2000" to "拳皇2000",
        "kof2001" to "拳皇2001",
        "kof2002" to "拳皇2002 - 挑战到极致",
        "kof2003" to "拳皇2003",
        "kof10th" to "拳皇十周年纪念版",
        "kof2k2um" to "拳皇2002 终极对决",
        "kof98um" to "拳皇98 终极对决",
        "kofxi" to "拳皇XI",
        "kofxii" to "拳皇XII",
        "kofxiii" to "拳皇XIII",

        // ========== SNK 合金弹头系列 (Metal Slug) ==========
        "mslug" to "合金弹头",
        "mslug2" to "合金弹头2",
        "mslug3" to "合金弹头3",
        "mslug4" to "合金弹头4",
        "mslug5" to "合金弹头5",
        "mslugx" to "合金弹头X",
        "mslug6" to "合金弹头6",
        "mslugp" to "合金弹头 完美版",

        // ========== SNK 侍魂系列 (Samurai Shodown) ==========
        "samsho" to "侍魂",
        "samsho2" to "侍魂 - 真侍魂剑客异闻录",
        "samsho3" to "侍魂 - 斩红郎无双剑",
        "samsho4" to "侍魂 - 天草降临",
        "samsho5" to "侍魂 - 零",
        "samsho5sp" to "侍魂 - 零 特别版",
        "samsho5s" to "侍魂 - 零 特别版",
        "samsho6" to "侍魂 - 天下第一剑客传",
        "samsride" to "侍魂 - 阿斯拉斩魔传",

        // ========== SNK 月华之剑士系列 (Last Blade) ==========
        "lastblad" to "月华之剑士",
        "lastbld2" to "月华之剑士2",

        // ========== SNK 恶狼传奇系列 (Fatal Fury) ==========
        "fatfury1" to "恶狼传奇",
        "fatfury2" to "恶狼传奇2",
        "fatfury3" to "恶狼传奇3 - 最终之战",
        "fatfursp" to "恶狼传奇 特别版",
        "fatfury3" to "恶狼传奇3 - 最终之战",
        "rbff1" to "真实恶狼传奇",
        "rbff2" to "真实恶狼传奇2",
        "rbffspec" to "真实恶狼传奇 特别版",
        "garou" to "饿狼 - 群狼之证",
        "garouh" to "饿狼 - 群狼之证",
        "garoubl" to "饿狼 - 群狼之证（魔改版）",

        // ========== SNK 龙虎之拳系列 (Art of Fighting) ==========
        "aof" to "龙虎之拳",
        "aof2" to "龙虎之拳2",
        "aof3" to "龙虎之拳3 - 龙狼之血",
        "aof3k" to "龙虎之拳3",

        // ========== SNK 其他对战 ==========
        "fightfev" to "风云默示录",
        "fightfeva" to "风云默示录",
        "sasukou" to "风云默示录2 - 奥义乱舞",
        "bjourney" to "战国传承3",
        "sengoku3" to "战国传承3",
        "sengoku" to "战国传承",
        "sengoku2" to "战国传承2",
        "kabukikl" to "月华之剑士 - 外传",
        "ninjamas" to "忍者大师",
        "pspikes" to "超级 Volley '94",
        "pspikes2" to "超级排球",
        "neogeo" to "NeoGeo BIOS",

        // ========== SNK 竞速 / 运动 ==========
        "ridhero" to "骑手英雄",
        "ridheroh" to "骑手英雄",
        "neodrift" to "Neo Drift Out",
        "overtop" to "Over Top 越野赛车",
        "twinspri" to "Twin Bee 双子精灵（街机）",
        "strhoop" to "街头扣篮",
        "socbrawl" to "足球争霸",
        "pdpsp" to "Power Spikes",

        // ========== SNK 益智 / 弹珠 / 休闲 ==========
        "joyjoy" to "Puzzle Joy Joy",
        "lbowling" to "League Bowling",
        "minasan" to "Minasan no Okeru",
        "puzzled" to "Puzzled",
        "puzldama" to "Puzzle Bobble 龙珠泡泡龙",
        "pbobbl2" to "泡泡龙2 - 龙珠Q",
        "pbobbl3" to "泡泡龙3",
        "pbobbl4" to "泡泡龙4",
        "pbobbln" to "泡泡龙 NeoGeo 版",
        "pbobbl2n" to "泡泡龙2 NeoGeo 版",
        "zupapa" to "ZuPaPa",
        "magdrop" to "Magical Drop 3",
        "magdro2" to "Magical Drop 2",
        "magdro3" to "Magical Drop 3",
        "marukod" to "丸子的暑假",

        // ========== SNK 射击 ==========
        "twinspri" to "Twin Bee 双子精灵",
        "twinksp" to "Twin Bee 双子精灵（SP）",
        "psoldier" to "Pulstar 战机",
        "blazstar" to "Blazing Star 烈火战机",
        "lasthope" to "Last Hope",
        "preisle2" to "Prehistoric Isle 2",

        // ========== Capcom CPS1 街头霸王系列 ==========
        "sf" to "街头霸王",
        "sf1" to "街头霸王",
        "sf2" to "街头霸王2 - 世界勇士",
        "sf2ce" to "街头霸王2' - 冠军版",
        "sf2hf" to "街头霸王2' - 加速版",
        "ssf2" to "超级街头霸王2",
        "ssf2t" to "超级街头霸王2X - 终极决战",
        "hsf2" to "超级街头霸王2 - 极速对决",
        "sf2hf" to "街头霸王2' - 加速版",
        "sf2cce" to "街头霸王2 - 冠军版",
        "sf2tlon" to "街头霸王2 - 彩虹版",
        "sf2stt" to "街头霸王2 - 超级加速版",
        "sf2b" to "街头霸王2 - 测试版",
        "sf2m1" to "街头霸王2 - 测试版",
        "sf2m2" to "街头霸王2 - 测试版",
        "sf2m3" to "街头霸王2 - 测试版",
        "sf2m4" to "街头霸王2 - 测试版",
        "sf2m5" to "街头霸王2 - 测试版",
        "sf2m6" to "街头霸王2 - 测试版",
        "sf2m7" to "街头霸王2 - 测试版",
        "sf2mdb" to "街头霸王2 - 测试版",
        "sf2mkot" to "街头霸王2 - 彩虹版",

        // ========== Capcom CPS1 其他对战 ==========
        "sfa" to "街头霸王ZERO",
        "sfa2" to "街头霸王ZERO2",
        "sfa3" to "街头霸王ZERO3",
        "sfz1" to "街头霸王ZERO",
        "sfz2" to "街头霸王ZERO2",
        "sfz3" to "街头霸王ZERO3",
        "sfz2al" to "街头霸王ZERO2 - α",
        "sfz3jr1" to "街头霸王ZERO3 - 测试版",
        "sfex" to "街头霸王EX",
        "sfex2" to "街头霸王EX2",
        "sfex2p" to "街头霸王EX2 Plus",
        "sfex3" to "街头霸王EX3",

        // ========== Capcom 街头霸王3 ==========
        "sfiii" to "街头霸王3 - 新世代",
        "sfiii2" to "街头霸王3 - 二度冲击",
        "sfiii3" to "街头霸王3 - 三度冲击",

        // ========== Capcom 漫画英雄 vs Capcom ==========
        "mvc" to "漫画英雄 vs Capcom - 英雄之战",
        "mvc2" to "漫画英雄 vs Capcom 2 - 新时代英雄",
        "mvsc" to "漫画英雄 vs Capcom - 英雄之战",
        "mvsc2" to "漫画英雄 vs Capcom 2",
        "xmvsf" to "X-Men vs 街头霸王",
        "avsp" to "异形大战铁血战士",
        "avsm" to "异形大战铁血战士",
        "nwarr" to "恶魔战士 - 吸血鬼之血",
        "vhunt2" to "恶魔战士2 - 吸血鬼猎人",
        "vsav" to "恶魔战士 - 吸血鬼救世主",
        "vsav2" to "恶魔战士 - 吸血鬼救世主2",
        "msh" to "漫画英雄 - Super Hero",
        "mshvsf" to "漫画英雄 vs 街头霸王",
        "mshvssf" to "漫画英雄 vs 街头霸王",

        // ========== Capcom CPS1 经典动作 ==========
        "ffight" to "快打旋风",
        "ffightua" to "快打旋风 - 美版",
        "ffightj" to "快打旋风 - 日版",
        "knights" to "圆桌骑士",
        "knightsj" to "圆桌骑士",
        "knightsh" to "圆桌骑士",
        "captcomm" to "美国队长 - 复仇者",
        "captcomu" to "美国队长",
        "captcomj" to "美国队长",
        "ddragon" to "双截龙",
        "ddragon2" to "双截龙2",
        "ddragon3" to "双截龙3 - 复仇",
        "ddragonb" to "双截龙 - NeoGeo 版",
        "ghouls" to "魔界村",
        "ghoulsu" to "魔界村 - 美版",
        "ghoulsj" to "魔界村 - 日版",
        "sgn" to "大魔界村",
        "sgnu" to "大魔界村 - 美版",
        "sgnj" to "大魔界村 - 日版",
        "strider" to "飞龙卫士",
        "stridrua" to "飞龙卫士",
        "striderh" to "飞龙卫士",
        "strider2" to "飞龙卫士2",
        "strider2u" to "飞龙卫士2",
        "bIONEER" to "Pioneer 飞龙",
        "forgottn" to "失落的世界",
        "lostwrld" to "失落的世界",
        "lw" to "失落的世界",

        // ========== Capcom CPS1 平台 / 横版 ==========
        "willow" to "魔女宅急便",
        "mercs" to "战场之狼2",
        "mercsu" to "战场之狼2",
        "mercsj" to "战场之狼2",
        "mtwins" to "魔法剑",
        "magicord" to "魔法剑士",
        "msword" to "魔法剑",
        "mswordu" to "魔法剑",
        "mswordj" to "魔法剑",
        "nick" to "Nick 兜风",

        // ========== Capcom CPS1 射击 ==========
        "varth" to "Varth - 雷电计划",
        "ecofght" to "Eco Fighters",
        "ecofighu" to "Eco Fighters",
        "pnick" to "Pnickies",
        "3wonders" to "三个奇迹",
        "3wundru" to "三个奇迹",
        "3wundrj" to "三个奇迹",
        "3wonderh" to "三个奇迹",
        "qad" to "Quiz & Dragons",
        "qadj" to "Quiz & Dragons",
        "qtono1" to "Quiz 三国志",
        "qtono2" to "Quiz 三国志2",
        "megaman" to "洛克人 - 街机版",
        "megamn2" to "洛克人2 - 力量对决",
        "rockman2" to "洛克人2 - 力量对决",
        "megamn2a" to "洛克人2 - 力量对决",
        "rockmanj" to "洛克人 - 街机版",

        // ========== Capcom CPS2 经典 ==========
        "progear" to "Progear - 飞旋镖",
        "progearj" to "Progear - 飞旋镖",
        "progearu" to "Progear - 飞旋镖",
        "gigawing" to "Giga Wing 鲨鲨",
        "gigawingj" to "Giga Wing 鲨鲨",
        "gigawing2" to "Giga Wing 2",
        "dimahoo" to "Dimahoo 魔法大作战",
        "dimahooj" to "Dimahoo 魔法大作战",
        "1944" to "1944 - 循环回路",
        "19xx" to "19XX - 战争战士",
        "19xxa" to "19XX - 战争战士",
        "19xxj" to "19XX - 战争战士",
        "19xxh" to "19XX - 战争战士",
        "marsmil" to "火星矩阵",
        "marsmilj" to "火星矩阵",
        "cybots" to "Cyberbots - 满舱金属战士",
        "cybotsj" to "Cyberbots - 满舱金属战士",
        "cybotsu" to "Cyberbots - 满舱金属战士",
        "armwar" to "Armored Warriors 装甲勇士",
        "armwaru" to "装甲勇士",
        "armwarj" to "装甲勇士",
        "pgear" to "装甲勇士",
        "batcir" to "Battle Circuit 战斗电路",
        "batcirj" to "Battle Circuit 战斗电路",
        "slammast" to "Saturday Night Slam Masters",
        "slammastu" to "Saturday Night Slam Masters",
        "slammastj" to "Saturday Night Slam Masters",
        "mbomber" to "Mighty! Pang 魔法泡泡",
        "mbomberj" to "Mighty! Pang 魔法泡泡",
        "pang3" to "魔法泡泡3",
        "pang3r1" to "魔法泡泡3",
        "pangpang" to "魔法泡泡",
        "bbuster" to "Block Block - 弹球",
        "bbustereu" to "Block Block - 弹球",
        "bbusterj" to "Block Block - 弹球",
        "pzloop2" to "Puzzle Loop 2 - 神奇泡泡",
        "pzloop2j" to "Puzzle Loop 2 - 神奇泡泡",
        "pzloop2u" to "Puzzle Loop 2 - 神奇泡泡",
        "mpang" to "魔法泡泡 - 魔法版",
        "mpangr1" to "魔法泡泡 - 魔法版",

        // ========== Capcom CPS3 ==========
        "jojo" to "JoJo的奇妙冒险",
        "jojoa" to "JoJo的奇妙冒险",
        "jojoba" to "JoJo的奇妙冒险 - 未来遗产",
        "jojobane" to "JoJo的奇妙冒险 - 未来遗产",
        "jojobanj" to "JoJo的奇妙冒险 - 未来遗产",
        "sfiii3n" to "街头霸王3 - 三度冲击",
        "sfiii3a" to "街头霸王3 - 三度冲击",
        "sfiii2a" to "街头霸王3 - 二度冲击",
        "warzard" to "红莲之王 - Warzard",
        "warzarda" to "红莲之王 - Warzard",
        "warzardj" to "红莲之王 - Warzard",

        // ========== IGS PGM 三国战纪系列 ==========
        "kov" to "三国战纪",
        "kov2" to "三国战纪2",
        "kovsh" to "三国战纪 - 风云再起",
        "kovplus" to "三国战纪 - 风云再起 Plus",
        "kovshp" to "三国战纪 - 一统中原",
        "kovshx" to "三国战纪 - 风云再起（魔改）",
        "kov2p" to "三国战纪2 Plus",
        "kov2x" to "三国战纪2 - 武将争霸",
        "kov2xx" to "三国战纪2 - 盖世英雄",
        "kovassg" to "三国战纪 - 群雄逐鹿",
        "kovshxp" to "三国战纪 - 风云再起 Plus",
        "kovshaa" to "三国战纪 - 风云再起",
        "kovshab" to "三国战纪 - 风云再起",
        "kovshac" to "三国战纪 - 风云再起",

        // ========== IGS PGM 西游释厄传 ==========
        "oriental" to "西游释厄传",
        "orlegend" to "西游释厄传",
        "orlegendc" to "西游释厄传 - 中文版",
        "orlegendca" to "西游释厄传 - 中文版",
        "orlegend111c" to "西游释厄传 - 1.11版",
        "orlegend105k" to "西游释厄传 - 1.05版",
        "olds" to "西游释厄传 - SUPER",
        "olds100" to "西游释厄传 - SUPER",
        "olds100a" to "西游释厄传 - SUPER",

        // ========== IGS PGM 其他 ==========
        "ddp2" to "怒首领蜂2 - 蜂暴",
        "ddp3" to "怒首领蜂3 - 大往生",
        "ddpdoj" to "怒首领蜂 - 大往生",
        "ddpdojp" to "怒首领蜂 - 大往生 Plus",
        "ddpdojt" to "怒首领蜂 - 大往生",
        "espgal" to "怒首领蜂 - 蜂暴",
        "espgal2" to "怒首领蜂 - 蜂暴2",
        "espgaluda" to "怒首领蜂 - 蜂暴",
        "espgaludb" to "怒首领蜂 - 蜂暴",
        "ket" to "怒首领蜂 - 大往生",
        "ketkb" to "怒首领蜂 - 大往生",
        "dsmbl" to "奇迹 мускуль",
        "puzzlepcs" to "PGM 泡泡龙 - 魔法消除",
        "puzzlepcsa" to "PGM 泡泡龙 - 魔法消除",
        "kovshpz" to "三国战纪 - 风云再起（魔改）",
        "svgons" to "形意拳",
        "svegons" to "形意拳",
        "killbld" to "神剑伏魔录",
        "killbldp" to "神剑伏魔录 - Plus",
        "killbld110" to "神剑伏魔录 - 1.10版",
        "theglad" to "神剑伏魔录",
        "thegladp" to "神剑伏魔录 - Plus",
        "gladiator" to "神剑伏魔录",
        "happy6" to "欢乐六仔",
        "happy6in1" to "欢乐六仔",
        "pgm3in1" to "PGM 三合一",
        "happy6100" to "欢乐六仔 1.00版",

        // ========== IGS 龙 ==========
        "dragon" to "龙行天下",
        "dragonworld" to "龙行天下",
        "dragonwrld" to "龙行天下",
        "dw" to "龙行天下",
        "drgwrld" to "龙行天下",
        "dwrld" to "龙行天下",

        // ========== IGS 其他 ==========
        "cryptklr" to "Crypt Killer",
        "sshooter" to "西游记 - 街机射击版",
        "ssword" to "神剑 - 街机版",

        // ========== 经典街机 - Namco ==========
        "pacman" to "吃豆人",
        "pacmanm" to "吃豆人 - 改版",
        "pacmod" to "吃豆人 - 速度版",
        "pacplus" to "吃豆人 - 加强版",
        "superpac" to "超级吃豆人",
        "pacnpal" to "吃豆人 - 派对版",
        "pacpal" to "吃豆人 - 派对版",
        "mspacman" to "Ms. Pac-Man 吃豆小姐",
        "mspacmat" to "Ms. Pac-Man 吃豆小姐",
        "pacmania" to "吃豆人 - 3D",
        "jrpacman" to "Jr. Pac-Man 小吃豆人",
        "galaga" to "大蜜蜂",
        "galagamw" to "大蜜蜂 - 改版",
        "galagamf" to "大蜜蜂 - 快速版",
        "galagads" to "大蜜蜂 - 双人版",
        "galaga88" to "大蜜蜂88",
        "galmidw" to "大蜜蜂 - 中版",
        "galmidu" to "大蜜蜂 - 美版",
        "galg88" to "大蜜蜂88",
        "galmort" to "大蜜蜂 - 改版",
        "gaplus" to "大蜜蜂 - 加强版",
        "galxwars" to "银河战争",
        "galxwar" to "银河战争",
        "gekir" to "激突 - 大蜜蜂2",
        "digdug" to "挖挖豆豆",
        "digdug2" to "挖挖豆豆2 - 危险的海底",
        "digdugat" to "挖挖豆豆 - 改版",
        "digdug1" to "挖挖豆豆",
        "mappy" to "Mappy 警察抓小偷",
        "mappyj" to "Mappy 警察抓小偷",
        "xevios" to "Xevious 银河战机",
        "xevious" to "Xevious 银河战机",
        "xeviousu" to "Xevious 银河战机",
        "xeviousj" to "Xevious 银河战机",
        "boslite" to "Bosconian 宇宙守卫",
        "bosco" to "Bosconian 宇宙守卫",
        "boscomd" to "Bosconian 宇宙守卫 - 改版",
        "toypop" to "玩具波普",
        "rompers" to "Rompers 推方块",
        "bombjack" to "炸弹杰克",
        "bombjack2" to "炸弹杰克2",

        // ========== 经典街机 - Taito ==========
        "bublbobl" to "泡泡龙",
        "bublboblr" to "泡泡龙 - 改版",
        "bublboblr2" to "泡泡龙 - 改版2",
        "boblbobl" to "泡泡龙",
        "sboblbobl" to "泡泡龙 - Super",
        "sboblboblr" to "泡泡龙 - Super",
        "bublprob" to "泡泡龙 - 真品版",
        "bublboblp" to "泡泡龙 - 真品版",
        "bublbobl1" to "泡泡龙 - 1代",
        "bublboblm" to "泡泡龙 - 改版",
        "bubsym" to "泡泡交响曲",
        "bubsymp" to "泡泡交响曲",
        "bubblem" to "泡泡记忆",
        "bubblemr" to "泡泡记忆 - 改版",
        "bubblep" to "泡泡龙 - 派对版",
        "bublbob2" to "泡泡龙2",
        "bublbobl2" to "泡泡龙2",
        "snowbros" to "雪人兄弟",
        "snowbroa" to "雪人兄弟 - 改版",
        "snowbrob" to "雪人兄弟 - 改版",
        "snowbroj" to "雪人兄弟 - 日版",
        "snowbro2" to "雪人兄弟2",
        "snowbr3" to "雪人兄弟3",
        "snowbro2j" to "雪人兄弟2 - 日版",
        "donpachi" to "怒首领蜂 - 初代",
        "donpachij" to "怒首领蜂 - 初代",
        "donpachi1" to "怒首领蜂 - 初代",
        "donpachh" to "怒首领蜂 - 初代",
        "ddonpach" to "怒首领蜂 - 初代",
        "ddonpachj" to "怒首领蜂 - 初代",
        "ddp" to "怒首领蜂",
        "arikanoid" to "打砖块 Arkanoid",
        "arkanoid" to "打砖块 Arkanoid",
        "arknoid2" to "打砖块 Arkanoid2 - 反击",
        "arkanoid2" to "打砖块 Arkanoid2 - 反击",
        "arkatour" to "打砖块 Arkanoid - 锦标赛",
        "arknoidu" to "打砖块 Arkanoid - 美版",
        "arknoidj" to "打砖块 Arkanoid - 日版",
        "rainbow" to "彩虹岛",
        "rainbowj" to "彩虹岛",
        "rainbowe" to "彩虹岛 - 额外版",
        "rainbowo" to "彩虹岛 - 老版",
        "lkage" to "传奇武士 - 影之传说",
        "lkageb" to "传奇武士 - 改版",
        "lkageo" to "传奇武士 - 老版",
        "kiwame" to "传奇武士 - 极",
        "darius" to "Darius 大流士",
        "darius2" to "Darius2 大流士2",
        "dariusg" to "Darius Gaiden 大流士外传",
        "dariusg2" to "Darius Gaiden 大流士外传",
        "dariusg2j" to "Darius Gaiden 大流士外传",
        "dariusgx" to "Darius Gaiden 大流士外传",
        "g_darius" to "G-Darius",
        "gdarius" to "G-Darius",
        "gdarius2" to "G-Darius2",
        "nightr" to "Night Striker",
        "nstrk" to "Night Striker",
        "nstrko" to "Night Striker",
        "spacegun" to "Space Gun",
        "spaceinv" to "太空侵略者",
        "spaceinv2" to "太空侵略者2",
        "invaders" to "太空侵略者",
        "invadpt2" to "太空侵略者 Part 2",

        // ========== 经典街机 - Konami ==========
        "contraj" to "魂斗罗 - 日版",
        "contra" to "魂斗罗",
        "contrar" to "魂斗罗 - 改版",
        "contrab" to "魂斗罗 - 改版",
        "contrajb" to "魂斗罗 - 改版",
        "contra1" to "魂斗罗",
        "gryzor" to "魂斗罗 - 欧版",
        "supercontra" to "超级魂斗罗",
        "supercontraj" to "超级魂斗罗 - 日版",
        "supercontrar" to "超级魂斗罗 - 改版",
        "scontra" to "超级魂斗罗",
        "scontraj" to "超级魂斗罗 - 日版",
        "tmnt" to "忍者神龟 - 街机版",
        "tmnt2" to "忍者神龟2 - 街机版",
        "tmnt22p" to "忍者神龟2 - 2P版",
        "tmht" to "忍者神龟 - 英文名版",
        "tmht2p" to "忍者神龟 - 2P版",
        "ssriders" to "日落骑士",
        "ssrider1" to "日落骑士",
        "ssrider2" to "日落骑士",
        "ssrider3" to "日落骑士",
        "ssrider4" to "日落骑士",
        "ssrider5" to "日落骑士",
        "ssrider6" to "日落骑士",
        "ssrideru" to "日落骑士 - 美版",
        "ssriderj" to "日落骑士 - 日版",
        "ssridere" to "日落骑士 - 欧版",
        "sunsetbl" to "日落骑士 - 魔改版",
        "sunsetb" to "日落骑士 - 魔改版",
        "xmen" to "X-Men 战警 - 街机版",
        "xmen2p" to "X-Men 战警 - 2P版",
        "xmen4p" to "X-Men 战警 - 4P版",
        "xmen6p" to "X-Men 战警 - 6P版",
        "xmenj" to "X-Men 战警 - 日版",
        "xmen6pa" to "X-Men 战警 - 6P版",
        "xmen6pj" to "X-Men 战警 - 6P版",
        "xmen6pu" to "X-Men 战警 - 6P版",
        "xmen6pe" to "X-Men 战警 - 6P版",
        "xmenusa" to "X-Men 战警 - 美版",
        "xmenjp" to "X-Men 战警 - 日版",
        "simpsons" to "辛普森一家",
        "simpson2p" to "辛普森一家 - 2P版",
        "simpson4p" to "辛普森一家 - 4P版",
        "simpsonj" to "辛普森一家 - 日版",
        "simpsonu" to "辛普森一家 - 美版",
        "parodius" to "Parodius 搞笑大战",
        "parodiusj" to "Parodius 搞笑大战",
        "parodiusr" to "Parodius 搞笑大战",
        "parodus2" to "Parodius 搞笑大战2",
        "parodiua" to "Parodius 搞笑大战",
        "gokuparo" to "Parodius 搞笑大战 - 极上",
        "gradius" to "Gradius 沙罗曼蛇",
        "gradius2" to "Gradius2 沙罗曼蛇2",
        "gradius3" to "Gradius3 沙罗曼蛇3",
        "gradius4" to "Gradius4 沙罗曼蛇4",
        "salamand" to "沙罗曼蛇 - Salamander",
        "salamand2" to "沙罗曼蛇2 - Salamander2",
        "lifefrce" to "Life Force 沙罗曼蛇 - 美版",
        "lifeforc" to "Life Force 沙罗曼蛇 - 美版",
        "neme" to "Nemesis 沙罗曼蛇",
        "neme2" to "Nemesis2 沙罗曼蛇",
        "vulcan" to "Vulcan Venture - 沙罗曼蛇",
        "vulcan2" to "Vulcan Venture - 沙罗曼蛇2",
        "mx5000" to "MX5000",
        "crimfight" to "Crime Fighters",
        "crimfgt2" to "Crime Fighters2",
        "crimfgtj" to "Crime Fighters - 日版",
        "mysticwar" to "神秘勇士",

        // ========== 经典街机 - Sega ==========
        "outrun" to "OutRun 突破极限",
        "outrunu" to "OutRun 突破极限 - 美版",
        "outrunj" to "OutRun 突破极限 - 日版",
        "outrunb" to "OutRun 突破极限 - 改版",
        "outruna" to "OutRun 突破极限",
        "turbooutrun" to "Turbo OutRun",
        "outrun2" to "OutRun 2",
        "outrun2sp" to "OutRun 2 - SP",
        "outrun2u" to "OutRun 2 - 美版",
        "outrun2j" to "OutRun 2 - 日版",
        "hangon" to "Hang-On 摩托",
        "hangon1" to "Hang-On 摩托",
        "hangon2" to "Hang-On 摩托",
        "hangonu" to "Hang-On 摩托 - 美版",
        "hangonsh" to "Hang-On 摩托 - Super",
        "shangon" to "Super Hang-On 摩托",
        "shangon2" to "Super Hang-On 摩托",
        "shangonu" to "Super Hang-On 摩托 - 美版",
        "shangonj" to "Super Hang-On 摩托 - 日版",
        "spacehar" to "太空哈利",
        "spacehar1" to "太空哈利",
        "spacehar2" to "太空哈利2",
        "spaceharu" to "太空哈利 - 美版",
        "spaceharj" to "太空哈利 - 日版",
        "aliens" to "异形 - 街机版",
        "aliens2" to "异形2 - 街机版",
        "aliensu" to "异形 - 美版",
        "aliensj" to "异形 - 日版",
        "aliene" to "异形 - 欧版",
        "aliensy" to "异形 - 改版",
        "aliens3" to "异形3",
        "astorm" to "Alien Storm 异形风暴",
        "astormu" to "Alien Storm 异形风暴 - 美版",
        "astormj" to "Alien Storm 异形风暴 - 日版",
        "astorme" to "Alien Storm 异形风暴 - 欧版",
        "eswat" to "E-SWAT 特警",
        "eswatu" to "E-SWAT 特警 - 美版",
        "eswatj" to "E-SWAT 特警 - 日版",
        "eswatcyb" to "E-SWAT 特警 - 改版",
        "moonwalker" to "迈克尔杰克逊 - 月球漫步",
        "moonwlku" to "迈克尔杰克逊 - 月球漫步",
        "moonwlkj" to "迈克尔杰克逊 - 月球漫步",
        "moonwlke" to "迈克尔杰克逊 - 月球漫步",
        "goldnaxe" to "战斧",
        "goldnaxeu" to "战斧 - 美版",
        "goldnaxej" to "战斧 - 日版",
        "goldnaxe2" to "战斧2",
        "goldnaxe3" to "战斧3",
        "goldnaxr1" to "战斧 - 改版",
        "goldnaxr2" to "战斧 - 改版",
        "ga" to "战斧",
        "ga2" to "战斧2",
        "ga3" to "战斧3",
        "shadowdar" to "Shadow Dancer 影舞者",
        "shadowd" to "Shadow Dancer 影舞者",
        "shadowdu" to "Shadow Dancer 影舞者 - 美版",
        "shadowdj" to "Shadow Dancer 影舞者 - 日版",
        "shinobi" to "Shinobi 忍者",
        "shinobi1" to "Shinobi 忍者",
        "shinobiu" to "Shinobi 忍者 - 美版",
        "shinobij" to "Shinobi 忍者 - 日版",
        "shinobiu" to "Shinobi 忍者 - 美版",
        "shinobl" to "Shinobi 忍者 - 改版",
        "shinobiv" to "Shinobi 忍者 - 改版",
        "shinobly" to "Shinobi 忍者 - 改版",
        "sjryu" to "Shinobi 忍者 - 龙版",
        "sjryua" to "Shinobi 忍者 - 龙版",
        "sjryuk" to "Shinobi 忍者 - 龙版",
        "sjryu1" to "Shinobi 忍者 - 龙版",
        "streetsm" to "街头暴力",
        "streetsm1" to "街头暴力",
        "streetsm2" to "街头暴力2",
        "streetsm3" to "街头暴力3",
        "streetsmu" to "街头暴力 - 美版",
        "streetsmj" to "街头暴力 - 日版",
        "alien3" to "异形3 - 街机版",
        "golem" to "Golem",

        // ========== Sega 经典射击 ==========
        "galaxy" to "Galaxy Force 银河战机",
        "galaxyf" to "Galaxy Force 银河战机",
        "galaxyf2" to "Galaxy Force2 银河战机",
        "gf2" to "Galaxy Force2 银河战机",
        "thndrblt" to "Thunder Force 雷电",
        "thndrbla" to "Thunder Force 雷电",
        "thndrblr" to "Thunder Force 雷电 - 改版",
        "tf" to "Thunder Force 雷电",
        "whirl" to "Whirlwind",

        // ========== 经典街机 - Midway / Atari ==========
        "mk" to "真人快打",
        "mkr" to "真人快打 - 改版",
        "mkl" to "真人快打 - 改版",
        "mk2" to "真人快打2",
        "mk2r" to "真人快打2 - 改版",
        "mk2l" to "真人快打2 - 改版",
        "mk3" to "真人快打3",
        "mk3r" to "真人快打3 - 改版",
        "mk3r20" to "真人快打3 - 2.0改版",
        "mk3r14" to "真人快打3 - 1.4改版",
        "umk3" to "终极真人快打3",
        "umk3r" to "终极真人快打3 - 改版",
        "umk3l" to "终极真人快打3 - 改版",
        "umk3p" to "终极真人快打3 - Plus",
        "mk4" to "真人快打4",
        "mk4p" to "真人快打4 - Plus",
        "mk4r" to "真人快打4 - 改版",
        "mk4l" to "真人快打4 - 改版",
        "narc" to "NARC 缉毒特警",
        "narc2" to "NARC2 缉毒特警2",
        "narc3" to "NARC3 缉毒特警3",
        "rampage" to "Rampage 大怪兽",
        "rampage2" to "Rampage2 大怪兽2",
        "rampagew" to "Rampage World Tour 环球大怪兽",
        "rampagwt" to "Rampage World Tour 环球大怪兽",
        "rampart" to "Rampart 城堡战争",
        "spyhnt2" to "Spy Hunter 2 间谍猎人2",
        "spyhunt" to "Spy Hunter 间谍猎人",
        "klax" to "Klax 彩色积木",
        "klax2" to "Klax2 彩色积木",
        "smashtv" to "Smash TV 砸碎电视",
        "smashtv2" to "Smash TV2 砸碎电视2",
        "totalcarn" to "Total Carnage 全面屠杀",
        "totalrn" to "Total Carnage 全面屠杀",
        "atari" to "Atari BIOS",
        "asteroid" to "Asteroids 陨石",
        "asteroid1" to "Asteroids 陨石",
        "asteroid2" to "Asteroids 陨石2",
        "asteroid3" to "Asteroids 陨石3",
        "astdelux" to "Asteroids Deluxe 陨石 - 豪华版",
        "astdelu1" to "Asteroids Deluxe 陨石 - 豪华版",
        "centipd" to "Centipede 蜈蚣",
        "centipdb" to "Centipede 蜈蚣 - 改版",
        "millipd" to "Millipede 千足虫",
        "missile" to "Missile Command 导弹指挥官",
        "missile2" to "Missile Command 导弹指挥官2",
        "missile1" to "Missile Command 导弹指挥官",
        "missilec" to "Missile Command 导弹指挥官",
        "tempest" to "Tempest 暴风雨",
        "tempest1" to "Tempest 暴风雨",
        "tempest2" to "Tempest 暴风雨2",
        "battlez" to "Battlezone 战场",
        "battlez1" to "Battlezone 战场",
        "starwars" to "星球大战 - 街机版",
        "starwar1" to "星球大战 - 街机版",
        "empire" to "帝国反击战 - 街机版",
        "empire1" to "帝国反击战 - 街机版",
        "returnj" to "绝地归来 - 街机版",

        // ========== 经典街机 - Williams ==========
        "joust" to "Joust 鸟骑士",
        "joust2" to "Joust2 鸟骑士2",
        "defender" to "Defender 守护者",
        "defender2" to "Defender2 守护者2 - Stargate",
        "defndr2" to "Defender2 守护者2 - Stargate",
        "stargate" to "Stargate 星际之门",
        "robotron" to "Robotron 2084 机器人战场",
        "robotrn" to "Robotron 2084 机器人战场",
        "robotrnl" to "Robotron 2084 机器人战场 - 改版",
        "bubbles" to "Bubbles 泡泡",
        "splat" to "Splat 涂鸦",

        // ========== NeoGeo 经典横版过关 ==========
        "tophunt" to "Top Hunter - 顶级猎手",
        "tophuntr" to "Top Hunter - 顶级猎手",
        "bstar" to "Burning Star 燃烧星辰",
        "burningf" to "Burning Fight 燃烧战火",
        "burningfh" to "Burning Fight 燃烧战火",
        "mutnat" to "Mutation Nation 变异国度",
        "ncommand" to "Ninja Commando 忍者突击队",
        "ncom" to "Ninja Commando 忍者突击队",
        "roboarmy" to "Robo Army 机器人大军",
        "roboarmyj" to "Robo Army 机器人大军",
        "b2b" to "Back to Back 背靠背",
        "savagere" to "Savage Reign 野蛮王朝",
        "savagrk" to "Savage Reign 野蛮王朝",
        "savagereb" to "Savage Reign 野蛮王朝",
        "kizuna" to "Kizuna Encounter 羁绊之战",
        "kizuna2" to "Kizuna Encounter 羁绊之战",
        "kizuna4p" to "Kizuna Encounter 羁绊之战 - 4P版",
        "kizunaj" to "Kizuna Encounter 羁绊之战",
        "kizuna4p" to "Kizuna Encounter 羁绊之战 - 4P版",
        "spcinv95" to "Space Invaders 95 太空侵略者95",
        "tws96" to "Twin Bee 双子精灵 96",

        // ========== NeoGeo 经典射击 ==========
        "viewpoin" to "Viewpoint 视点",
        "viewpoinj" to "Viewpoint 视点",
        "asco" to "ASO - 雷霆战机 II",
        "ascott" to "Alpha Denshi - 战机",
        "alpham2" to "Alpha Mission II",
        "alpham2a" to "Alpha Mission II",
        "alphm2p" to "Alpha Mission II - Plus",
        "skyadvnt" to "Sky Adventure 天空冒险",
        "skyadvnu" to "Sky Adventure 天空冒险",
        "skyadvnj" to "Sky Adventure 天空冒险",
        "ghostlop" to "Ghostlop - 鬼球",
        "shocktr1" to "Shock Troopers 突击骑兵",
        "shocktr2" to "Shock Troopers 2 突击骑兵2",
        "shcktra" to "Shock Troopers 突击骑兵",
        "shocktro" to "Shock Troopers 突击骑兵",
        "shcktr2" to "Shock Troopers 2 突击骑兵2",
        "shcktrb" to "Shock Troopers 2 突击骑兵2",

        // ========== NeoGeo 体育运动 ==========
        "neocup98" to "Neo Geo Cup 98",
        "neocup98h" to "Neo Geo Cup 98",
        "ssideki" to "Super Sidekicks 热血足球",
        "ssideki2" to "Super Sidekicks 2 热血足球2",
        "ssideki3" to "Super Sidekicks 3 热血足球3",
        "ssideki4" to "Super Sidekicks 4 - 最终之战",
        "ssidek2" to "Super Sidekicks 2 热血足球2",
        "ssidek3" to "Super Sidekicks 3 热血足球3",
        "ssidek4" to "Super Sidekicks 4 - 最终之战",
        "ssrpg" to "Super Sidekicks RPG",
        "3countb" to "3 Count Bout - 摔角",
        "3countba" to "3 Count Bout - 摔角",
        "doubledr" to "Double Dragon - NeoGeo 版",
        "dbl_drg" to "Double Dragon - NeoGeo 版",
        "preisle" to "Prehistoric Island 史前岛",
        "preisle2" to "Prehistoric Island 2 史前岛2",
        "spinmast" to "Spin Master - 旋转大师",
        "spinmastu" to "Spin Master - 旋转大师",
        "spinmastj" to "Spin Master - 旋转大师",
        "marukodq" to "丸子之暑假 - 大魔王",
        "zedblade" to "Zed Blade - 雷霆战机",
        "zedblad" to "Zed Blade - 雷霆战机",
        "zedbladea" to "Zed Blade - 雷霆战机",

        // ========== 经典射击 - Raizing / Cave ==========
        "batrider" to "Battle Garegga - 战斗 Garaga",
        "batsugu" to "Battle Garegga - 战斗 Garaga",
        "bgaregga" to "Battle Garegga - 战斗 Garaga",
        "bgareggah" to "Battle Garegga - 战斗 Garaga",
        "bgareggan" to "Battle Garegga - 战斗 Garaga",
        "bgareggabl" to "Battle Garegga - 战斗 Garaga - 魔改",
        " Armedp" to "Armed Police Batrider",
        "batrider" to "Armed Police Batrider - 全副武装的警察",
        "batridr" to "Armed Police Batrider - 全副武装的警察",
        "batridra" to "Armed Police Batrider - 全副武装的警察",
        "batridrj" to "Armed Police Batrider - 全副武装的警察",
        "batridrb" to "Armed Police Batrider - 全副武装的警察",
        "batridrn" to "Armed Police Batrider - 全副武装的警察",
        "batridrbl" to "Armed Police Batrider - 全副武装的警察 - 魔改",
        "guwange" to "Guwange - 战国自卫队",
        "guwangej" to "Guwange - 战国自卫队",
        "guwangea" to "Guwange - 战国自卫队",
        "esprade" to "Esp Ra.De. - 炎之特工",
        "espradej" to "Esp Ra.De. - 炎之特工",
        "espradea" to "Esp Ra.De. - 炎之特工",
        "espradek" to "Esp Ra.De. - 炎之特工",
        "ddpdfk" to "怒首领蜂 - 大往生 Black Label",
        "ddpdfk10" to "怒首领蜂 - 大往生 Black Label 1.0",
        "ddpdfk15" to "怒首领蜂 - 大往生 Black Label 1.5",
        "mushitam" to "虫姬 - 蘑菇大战",
        "mushisam" to "虫姬 - 蘑菇大战",
        "mushisama" to "虫姬 - 蘑菇大战",
        "mushisgala" to "虫姬 - 蘑菇大战",
        "mushisama" to "虫姬 - 蘑菇大战",
        "futari10" to "虫姬双胞胎 1.0",
        "futari15" to "虫姬双胞胎 1.5",
        "deathsm" to "死亡微笑",
        "deathsmiles" to "死亡微笑",
        "deathsmile" to "死亡微笑",
        "deathsmil" to "死亡微笑",
        "deathsm2" to "死亡微笑2",
        "deathsmiles2" to "死亡微笑2",
        "ibara" to "Ibara - 玫瑰花园",
        "ibarab" to "Ibara - 玫瑰花园 - Black Label",
        "ibarabl" to "Ibara - 玫瑰花园 - Black Label",
        "ibara1" to "Ibara - 玫瑰花园 1.0",
        "ibara15" to "Ibara - 玫瑰花园 1.5",
        "ibarabk" to "Ibara - 玫瑰花园 Black Label",
        "ibaraes" to "Ibara - 玫瑰花园 - 杀人事件",
        "pinkswts" to "Pink Sweets - 粉色甜心",
        "pinkswts1" to "Pink Sweets - 粉色甜心",
        "crimzon" to "Crimzon Clover - 赤色三叶草",
        "crimclover" to "Crimzon Clover - 赤色三叶草",
        "akai" to "Akai Katana - 红色刀",
        "akai1" to "Akai Katana - 红色刀 1.0",
        "akai15" to "Akai Katana - 红色刀 1.5",
        "akaikat" to "Akai Katana - 红色刀",

        // ========== 经典射击 - Toaplan ==========
        "truxton" to "Truxton - 雷霆战机",
        "truxton2" to "Truxton2 - 雷霆战机2",
        "truxtn2" to "Truxton2 - 雷霆战机2",
        "tatsujin" to "Tatsujin - 龙神",
        "tatsujin2" to "Tatsujin2 - 龙神2",
        "tatsujin3" to "Tatsujin3 - 龙神3",
        "tatsujinm" to "Tatsujin - 龙神 - 改版",
        "tatsujinm2" to "Tatsujin2 - 龙神2 - 改版",
        "hellfire" to "Hellfire - 地狱火",
        "hellfire1" to "Hellfire - 地狱火",
        "hellfirej" to "Hellfire - 地狱火 - 日版",
        "hellfireu" to "Hellfire - 地狱火 - 美版",
        "hellfiree" to "Hellfire - 地狱火 - 欧版",
        "fireshark" to "Fire Shark - 火鲨",
        "fireshrk" to "Fire Shark - 火鲨",
        "fireshrku" to "Fire Shark - 火鲨 - 美版",
        "fireshrkj" to "Fire Shark - 火鲨 - 日版",
        "samesame" to "Same! Same! Same! - 火鲨",
        "samesame2" to "Same! Same! Same! - 火鲨2",
        "vimana" to "Vimana - 飞天战车",
        "vimana1" to "Vimana - 飞天战车",
        "vimanaj" to "Vimana - 飞天战车 - 日版",
        "vimana1u" to "Vimana - 飞天战车 - 美版",
        "outzone" to "Out Zone - 异形",
        "outzone1" to "Out Zone - 异形",
        "outzoneu" to "Out Zone - 异形 - 美版",
        "outzonej" to "Out Zone - 异形 - 日版",
        "zerowing" to "Zero Wing - 零式战机",
        "zerowing1" to "Zero Wing - 零式战机",
        "zerowingj" to "Zero Wing - 零式战机 - 日版",
        "zerowingk" to "Zero Wing - 零式战机 - 韩版",
        "zerowingw" to "Zero Wing - 零式战机 - 世界版",
        "zerowing2" to "Zero Wing2 - 零式战机2",
        "snowbro2" to "雪人兄弟2",
        "dogyuun" to "Dogyuun - 怒首领蜂风格",
        "dogyuun1" to "Dogyuun - 怒首领蜂风格",
        "dogyuunt" to "Dogyuun - 怒首领蜂风格 - 改版",
        "dogyuunu" to "Dogyuun - 怒首领蜂风格 - 美版",
        "dogyuunj" to "Dogyuun - 怒首领蜂风格 - 日版",
        "tekipaki" to "Teki Paki - 黄金扑克",
        "tekipaki1" to "Teki Paki - 黄金扑克",
        "tekipakit" to "Teki Paki - 黄金扑克 - 改版",
        "ghox" to "Ghox - 弹球",
        "ghox1" to "Ghox - 弹球",
        "ghoxj" to "Ghox - 弹球 - 日版",
        "pipibibs" to "Pipi & Bibi - 双人射击",
        "pipibibi" to "Pipi & Bibi - 双人射击",
        "pipibibs1" to "Pipi & Bibi - 双人射击",
        "whoopee" to "Whoopee!! - 笑翻天",
        "whoopee1" to "Whoopee!! - 笑翻天",
        "whoopeej" to "Whoopee!! - 笑翻天 - 日版",
        "whoopee2" to "Whoopee!!2 - 笑翻天2",
        "pengo" to "Pengo - 企鹅推冰",
        "pengo2" to "Pengo - 企鹅推冰2",
        "pengo1" to "Pengo - 企鹅推冰",
        "pengob" to "Pengo - 企鹅推冰 - 改版",
        "pengoj" to "Pengo - 企鹅推冰 - 日版",
        "pengou" to "Pengo - 企鹅推冰 - 美版",

        // ========== 经典射击 - Psikyo ==========
        "s1945" to "Strikers 1945 - 战机1945",
        "s1945a" to "Strikers 1945 - 战机1945",
        "s1945j" to "Strikers 1945 - 战机1945",
        "s1945k" to "Strikers 1945 - 战机1945",
        "s1945ii" to "Strikers 1945 II - 战机1945 II",
        "s1945iia" to "Strikers 1945 II - 战机1945 II",
        "s1945iii" to "Strikers 1945 III - 战机1945 III",
        "s1945iiia" to "Strikers 1945 III - 战机1945 III",
        "s1945p" to "Strikers 1945 Plus - 战机1945 Plus",
        "s1945pa" to "Strikers 1945 Plus - 战机1945 Plus",
        "sengokuace" to "战国 Ace - 战国王牌",
        "sengokua" to "战国 Ace - 战国王牌",
        "sngkace" to "战国 Ace - 战国王牌",
        "sngkacea" to "战国 Ace - 战国王牌",
        "sngkacej" to "战国 Ace - 战国王牌 - 日版",
        "sengokuace" to "战国 Ace - 战国王牌",
        "sengokb" to "战国之刃",
        "sengokublade" to "战国之刃",
        "sngkbld" to "战国之刃",
        "sngkblda" to "战国之刃",
        "sngkbldb" to "战国之刃",
        "sngkbldj" to "战国之刃 - 日版",
        "gunbird" to "Gunbird - 钢鸟",
        "gunbird1" to "Gunbird - 钢鸟",
        "gunbirdj" to "Gunbird - 钢鸟 - 日版",
        "gunbirda" to "Gunbird - 钢鸟",
        "gunbird2" to "Gunbird2 - 钢鸟2",
        "gunbird2a" to "Gunbird2 - 钢鸟2",
        "gunbird2j" to "Gunbird2 - 钢鸟2 - 日版",
        "gn_2" to "Gunbird2 - 钢鸟2",
        "gnbd2" to "Gunbird2 - 钢鸟2",
        "tengai" to "Tengai - 战国之刃2",
        "tengai1" to "Tengai - 战国之刃2",
        "tengaij" to "Tengai - 战国之刃2 - 日版",
        "tengaia" to "Tengai - 战国之刃2",
        "soldivid" to "Sol Divide - 剑与魔法",
        "soldivid1" to "Sol Divide - 剑与魔法",
        "soldividj" to "Sol Divide - 剑与魔法 - 日版",
        "soldivida" to "Sol Divide - 剑与魔法",
        "daraku" to "Daraku - 堕落",
        "daraku1" to "Daraku - 堕落",
        "darakuu" to "Daraku - 堕落 - 美版",
        "darakuaj" to "Daraku - 堕落 - 日版",
        "darakuaf" to "Daraku - 堕落",
        "darakuak" to "Daraku - 堕落 - 韩版",
        "dragblz" to "Dragon Blaze - 火龙",
        "dragblz1" to "Dragon Blaze - 火龙",
        "dragblzj" to "Dragon Blaze - 火龙 - 日版",
        "dragblza" to "Dragon Blaze - 火龙",
        "dragblzk" to "Dragon Blaze - 火龙 - 韩版",
        "hotd" to "House of the Dead - 死亡之屋",
        "hotd1" to "House of the Dead - 死亡之屋",
        "hotd2" to "House of the Dead2 - 死亡之屋2",
        "hotd2o" to "House of the Dead2 - 死亡之屋2 - 原版",

        // ========== 经典街机 - Irem ==========
        "rtype" to "R-Type - 雷霆战机",
        "rtypeu" to "R-Type - 雷霆战机 - 美版",
        "rtypej" to "R-Type - 雷霆战机 - 日版",
        "rtypee" to "R-Type - 雷霆战机 - 欧版",
        "rtype2" to "R-Type 2 - 雷霆战机2",
        "rtype2u" to "R-Type 2 - 雷霆战机2 - 美版",
        "rtype2j" to "R-Type 2 - 雷霆战机2 - 日版",
        "rtype2e" to "R-Type 2 - 雷霆战机2 - 欧版",
        "rtypeleo" to "R-Type Leo - 雷霆战机 Leo",
        "rtypeleoj" to "R-Type Leo - 雷霆战机 Leo",
        "rtype3" to "R-Type 3 - 雷霆战机3",
        "rtype3u" to "R-Type 3 - 雷霆战机3 - 美版",
        "rtype3j" to "R-Type 3 - 雷霆战机3 - 日版",
        "rtype3a" to "R-Type 3 - 雷霆战机3 - 改版",
        "rtype3a2" to "R-Type 3 - 雷霆战机3 - 改版2",
        "rthun2" to "R-Type Leo - 雷霆战机 Leo",
        "inthunt" to "In The Hunt - 海底神兵",
        "inthuntu" to "In The Hunt - 海底神兵 - 美版",
        "inthuntj" to "In The Hunt - 海底神兵 - 日版",
        "gunforc2" to "Gun Force 2 - 钢铁力量2",
        "gunforc" to "Gun Force - 钢铁力量",
        "gunforc2u" to "Gun Force 2 - 钢铁力量2",
        "gunforc2j" to "Gun Force 2 - 钢铁力量2",
        "gunhazard" to "Gun Hazard - 钢铁危机",

        // ========== 经典射击 - Seibu Kaihatsu ==========
        "raiden" to "雷电",
        "raidena" to "雷电",
        "raidenk" to "雷电 - 韩版",
        "raident" to "雷电 - 改版",
        "raiden2" to "雷电2",
        "raiden2a" to "雷电2",
        "raiden2j" to "雷电2 - 日版",
        "raiden2k" to "雷电2 - 韩版",
        "raiden2o" to "雷电2 - 原版",
        "raiden2p" to "雷电2 - Plus",
        "raiden2c" to "雷电2 - 中文版",
        "raiden3" to "雷电3",
        "raiden4" to "雷电4",
        "raiden4o" to "雷电4 - 原版",
        "raident2" to "雷电2",
        "raidndx" to "雷电 - DX",
        "raidndxj" to "雷电 - DX - 日版",
        "raidndxu" to "雷电 - DX - 美版",
        "raidndxa" to "雷电 - DX",
        "raidndx2" to "雷电 - DX 2",
        "raidndxo" to "雷电 - DX - 原版",
        "raidnfo" to "雷电 - V",
        "raidnfk" to "雷电 - V - 韩版",
        "raidnfj" to "雷电 - V - 日版",
        "raidnfv2" to "雷电 - V 2",
        "raidnfv2j" to "雷电 - V 2 - 日版",
        "raidnfv2a" to "雷电 - V 2",
        "viprphase" to "Viper Phase 1 - 毒蛇阶段",
        "viprphase1" to "Viper Phase 1 - 毒蛇阶段",
        "viprphasj" to "Viper Phase 1 - 毒蛇阶段 - 日版",
        "viprphasu" to "Viper Phase 1 - 毒蛇阶段 - 美版",
        "viprphasea" to "Viper Phase 1 - 毒蛇阶段",
        "senkyu" to "Senkyu - 战球",
        "senkyua" to "Senkyu - 战球",
        "senkyuj" to "Senkyu - 战球 - 日版",
        "senkyu2" to "Senkyu2 - 战球2",
        "senkyu2a" to "Senkyu2 - 战球2",
        "senkyu2j" to "Senkyu2 - 战球2 - 日版",

        // ========== 经典街机 - Tecmo ==========
        "tecmo" to "Tecmo - 街机合集",
        "rygar" to "Tecmo - 龙骑士",
        "rygar1" to "Tecmo - 龙骑士",
        "rygar2" to "Tecmo - 龙骑士2",
        "rygarj" to "Tecmo - 龙骑士 - 日版",
        "rygaru" to "Tecmo - 龙骑士 - 美版",
        "tecmowr" to "Tecmo World Wrestling - 摔角",
        "tecmowr1" to "Tecmo World Wrestling - 摔角",
        "tecmowrj" to "Tecmo World Wrestling - 摔角 - 日版",
        "tecmowru" to "Tecmo World Wrestling - 摔角 - 美版",
        "tbowl" to "Tecmo Bowl - 美式足球",
        "tbowl1" to "Tecmo Bowl - 美式足球",
        "tbowlj" to "Tecmo Bowl - 美式足球 - 日版",
        "tbowl2" to "Tecmo Bowl2 - 美式足球2",
        "tecmo杯" to "Tecmo 杯 - 足球",
        "soccer" to "Tecmo - 足球",
        "ninjagaidn" to "忍者龙剑传 - 街机版",
        "ninjagaidn1" to "忍者龙剑传 - 街机版",
        "ninjagaidnj" to "忍者龙剑传 - 街机版 - 日版",
        "ninjagaidnu" to "忍者龙剑传 - 街机版 - 美版",

        // ========== 经典街机 - Koei / 其他 ==========
        "puzbobb" to "Puzzle Bobble - 泡泡龙",
        "puzbob" to "Puzzle Bobble - 泡泡龙",
        "puzbob2" to "Puzzle Bobble2 - 泡泡龙2",
        "bounty" to "Bounty - 海盗宝藏",
        "stakwin" to "Stakes Winner - 赛马",
        "stakwin2" to "Stakes Winner2 - 赛马2",
        "stakwin1" to "Stakes Winner - 赛马",
        "ghand" to "Golden Hand - 黄金手",
        "gtmr" to "Great Thief - 大盗",
        "gtmr2" to "Great Thief2 - 大盗2",
        "piratpet" to "Pirate Pete - 海盗皮特",

        // ========== 数据 East 经典 ==========
        "karnov" to "Karnov - 卡尔诺夫",
        "karnovj" to "Karnov - 卡尔诺夫 - 日版",
        "karnovu" to "Karnov - 卡尔诺夫 - 美版",
        "karnovr" to "Karnov - 卡尔诺夫 - 改版",
        "karnovl" to "Karnov - 卡尔诺夫 - 改版",
        "chelnov" to "Chelnov - 原子战士",
        "chelnovj" to "Chelnov - 原子战士 - 日版",
        "chelnovu" to "Chelnov - 原子战士 - 美版",
        "chelnove" to "Chelnov - 原子战士 - 欧版",
        "darkseal" to "Dark Seal - 黑暗封印",
        "darkseal1" to "Dark Seal - 黑暗封印",
        "darksealj" to "Dark Seal - 黑暗封印 - 日版",
        "darksealu" to "Dark Seal - 黑暗封印 - 美版",
        "gateofdo" to "Gate of Doom - 末日之门",
        "gateofdo1" to "Gate of Doom - 末日之门",
        "gateofdoj" to "Gate of Doom - 末日之门 - 日版",
        " gateofdou" to "Gate of Doom - 末日之门 - 美版",
        "tumblep" to "Tumble Pop - 雪人兄弟风格",
        "tumblep1" to "Tumble Pop - 雪人兄弟风格",
        "tumblepj" to "Tumble Pop - 雪人兄弟风格 - 日版",
        "tumblepu" to "Tumble Pop - 雪人兄弟风格 - 美版",
        "tumblep2" to "Tumble Pop2 - 雪人兄弟风格2",
        "tumblepb" to "Tumble Pop - 雪人兄弟风格 - 改版",
        "dietgo" to "Diet Go - 减肥哥",
        "dietgo1" to "Diet Go - 减肥哥",
        "dietgoj" to "Diet Go - 减肥哥 - 日版",
        "dietgou" to "Diet Go - 减肥哥 - 美版",
        "bouldsh" to "Boulder Dash - 巨石阵",
        "bouldsh1" to "Boulder Dash - 巨石阵",
        "bouldshj" to "Boulder Dash - 巨石阵 - 日版",
        "maglor" to "Magical Drop - 魔法气球",
        "maglor1" to "Magical Drop - 魔法气球",
        "maglor2" to "Magical Drop2 - 魔法气球2",
        "maglor3" to "Magical Drop3 - 魔法气球3",
        "chainrec" to "Chain Reaction - 连锁反应",
        "chainrec1" to "Chain Reaction - 连锁反应",
        "chainrecj" to "Chain Reaction - 连锁反应 - 日版",

        // ========== 经典益智 ==========
        "tetric" to "Tetris - 俄罗斯方块",
        "tetris" to "Tetris - 俄罗斯方块",
        "tetris1" to "Tetris - 俄罗斯方块",
        "tetris2" to "Tetris2 - 俄罗斯方块2",
        "tetrisa" to "Tetris - 俄罗斯方块",
        "tetrisj" to "Tetris - 俄罗斯方块 - 日版",
        "tetrisu" to "Tetris - 俄罗斯方块 - 美版",
        "atetris" to "Atari Tetris - 俄罗斯方块",
        "atetris1" to "Atari Tetris - 俄罗斯方块",
        "atetrise" to "Atari Tetris - 俄罗斯方块 - 欧版",
        "pptigr" to "Puzzle - 龙珠Q",
        "ppang" to "Puzzle - 魔法泡泡 NeoGeo",

        // ========== 经典 Misc ==========
        "1942" to "1942 - 太平洋之战",
        "1942a" to "1942 - 太平洋之战",
        "1942j" to "1942 - 太平洋之战 - 日版",
        "1942k" to "1942 - 太平洋之战 - 韩版",
        "1943" to "1943 - 中途岛海战",
        "1943a" to "1943 - 中途岛海战",
        "1943j" to "1943 - 中途岛海战 - 日版",
        "1943kai" to "1943 Kai - 中途岛海战 - 改版",
        "1943k" to "1943 - 中途岛海战 - 韩版",
        "1943u" to "1943 - 中途岛海战 - 美版",
        "commando" to "Commando - 突击队员",
        "commando1" to "Commando - 突击队员",
        "commandoj" to "Commando - 突击队员 - 日版",
        "commandou" to "Commando - 突击队员 - 美版",
        "commandob" to "Commando - 突击队员 - 改版",
        "gng" to "魔界村 - Ghost'n Goblins",
        "gnga" to "魔界村 - Ghost'n Goblins",
        "gngj" to "魔界村 - Ghost'n Goblins - 日版",
        "gngt" to "魔界村 - Ghost'n Goblins - 改版",
        "sgng" to "大魔界村 - Ghosts'n Goblins",
        "sgnga" to "大魔界村 - Ghosts'n Goblins",
        "sgngj" to "大魔界村 - Ghosts'n Goblins - 日版",
        "gaires" to "Giga Wing - 鲨鲨",
        "tadopt" to "Tron - 电子世界争霸战",
        "tron" to "Tron - 电子世界争霸战",
        "tron1" to "Tron - 电子世界争霸战",
        "tron2" to "Tron - 电子世界争霸战2",
        "tron3" to "Tron - 电子世界争霸战3",
        "tron4" to "Tron - 电子世界争霸战4",

        // ========== NeoGeo BIOS & 集合 ==========
        "neogeo" to "NeoGeo BIOS",
        "neogeocd" to "NeoGeo CD BIOS",
        "neogeocdj" to "NeoGeo CD BIOS",
        "mvs" to "NeoGeo MVS",
        "aes" to "NeoGeo AES",

        // ========== 早期街机经典 ==========
        "donkeykong" to "大金刚",
        "donkeykongj" to "大金刚 - 日版",
        "donkeykongb" to "大金刚 - 改版",
        "dkong" to "大金刚",
        "dkongj" to "大金刚 - 日版",
        "dkongjr" to "大金刚 JR",
        "dkongjrj" to "大金刚 JR - 日版",
        "dkongjrb" to "大金刚 JR - 改版",
        "dkong3" to "大金刚3",
        "dkong3j" to "大金刚3 - 日版",
        "mario" to "马里奥兄弟",
        "mario1" to "马里奥兄弟",
        "marioj" to "马里奥兄弟 - 日版",
        "mariob" to "马里奥兄弟 - 改版",
        "mario2" to "马里奥兄弟2",
        "mario3" to "马里奥兄弟3",
        "suprmrio" to "超级马里奥兄弟",
        "suprmriou" to "超级马里奥兄弟 - 美版",
        "suprmrioj" to "超级马里奥兄弟 - 日版",
        "suprmriok" to "超级马里奥兄弟 - 韩版",
        "mario_kart" to "马里奥赛车",
        "iceclimb" to "Ice Climber - 雪人爬山",
        "iceclimber" to "Ice Climber - 雪人爬山",
        "iceclimbr" to "Ice Climber - 雪人爬山 - 改版",
        "excitebk" to "Excitebike - 越野摩托",
        "excitebkj" to "Excitebike - 越野摩托 - 日版",
        "excitebku" to "Excitebike - 越野摩托 - 美版",
        "balloon" to "Balloon Fight - 气球大战",
        "balloonf" to "Balloon Fight - 气球大战",
        "balloon1" to "Balloon Fight - 气球大战",
        "balloonj" to "Balloon Fight - 气球大战 - 日版",
        "cluclu" to "Clu Clu Land - 珍珠猎人",
        "clucluw" to "Clu Clu Land - 珍珠猎人",
        "cluclu1" to "Clu Clu Land - 珍珠猎人",
        "urban" to "Urban Champion - 都市战士",
        "urban1" to "Urban Champion - 都市战士",
        "urbanj" to "Urban Champion - 都市战士 - 日版",
        "punchout" to "Punch-Out!! - 拳击",
        "punchout1" to "Punch-Out!! - 拳击",
        "punchoutj" to "Punch-Out!! - 拳击 - 日版",
        "spunchout" to "Super Punch-Out!! - 超级拳击",
        "spunchout1" to "Super Punch-Out!! - 超级拳击",
        "spunchoutj" to "Super Punch-Out!! - 超级拳击 - 日版",

        // ========== 经典射击 - Misc ==========
        "xevious" to "Xevious - 银河战机",
        "xevious1" to "Xevious - 银河战机",
        "xeviousj" to "Xevious - 银河战机 - 日版",
        "xeviousu" to "Xevious - 银河战机 - 美版",
        "xeviousa" to "Xevious - 银河战机",
        "xevious3d" to "Xevious 3D/G+ - 银河战机 3D",
        "sxevious" to "Super Xevious - 超级银河战机",
        "sxevious1" to "Super Xevious - 超级银河战机",
        "sxeviousj" to "Super Xevious - 超级银河战机 - 日版",
        "mappy" to "Mappy - 警察抓小偷",
        "mappy1" to "Mappy - 警察抓小偷",
        "mappyj" to "Mappy - 警察抓小偷 - 日版",
        "galaga" to "Galaga - 大蜜蜂",
        "galaga1" to "Galaga - 大蜜蜂",
        "galagao" to "Galaga - 大蜜蜂 - 原版",
        "galagam" to "Galaga - 大蜜蜂 - 改版",
        "galagamw" to "Galaga - 大蜜蜂 - 改版W",
        "galagams" to "Galaga - 大蜜蜂 - 速度版",
        "galagamf" to "Galaga - 大蜜蜂 - 速度版F",
        "galmidw" to "Galaga - 大蜜蜂 - 改版W",
        "galmidwo" to "Galaga - 大蜜蜂 - 改版W - 原版",
        "galmidw1" to "Galaga - 大蜜蜂 - 改版W",
        "galmort" to "Galaga - 大蜜蜂 - 改版T",
        "galmort1" to "Galaga - 大蜜蜂 - 改版T",
        "galaga3" to "Galaga 3 - 大蜜蜂3",
        "gaplus" to "Gaplus - 大蜜蜂加强版",
        "gapluso" to "Gaplus - 大蜜蜂加强版 - 原版",
        "gaplusa" to "Gaplus - 大蜜蜂加强版",
        "gaplusj" to "Gaplus - 大蜜蜂加强版 - 日版",

        // ========== NeoGeo 拳击/运动 ==========
        "boxing" to "Boxing - 拳击",
        "boxing1" to "Boxing - 拳击",
        "boxing2" to "Boxing2 - 拳击2",
        "boxingj" to "Boxing - 拳击 - 日版",

        // ========== 其他经典 ==========
        "qbert" to "Q*bert - 跳跳虫",
        "qbert1" to "Q*bert - 跳跳虫",
        "qbertj" to "Q*bert - 跳跳虫 - 日版",
        "qberta" to "Q*bert - 跳跳虫",
        "frogger" to "Frogger - 青蛙过河",
        "frogger1" to "Frogger - 青蛙过河",
        "froggerj" to "Frogger - 青蛙过河 - 日版",
        "froggr2" to "Frogger2 - 青蛙过河2",
        "froggrsw" to "Frogger - 青蛙过河 - SW版",
        "scramble" to "Scramble - 急速突袭",
        "scramble1" to "Scramble - 急速突袭",
        "scrambleb" to "Scramble - 急速突袭 - 改版",
        "scobra" to "Scramble - 改版",
        "scobras" to "Scramble - 改版",
        "scobrase" to "Scramble - 改版 - 欧版",
        "superbon" to "Super Bomberman - 超级炸弹人",
        "bomberman" to "炸弹人",
        "bombermn2" to "炸弹人2",
        "bombermn3" to "炸弹人3",
        "bombermnj" to "炸弹人 - 日版",
        "bombermanj" to "炸弹人 - 日版",
        "bomberman" to "炸弹人",
        "hishouzame" to "飞龙 - 飞翔斩",
        "hishouz" to "飞龙 - 飞翔斩",
        "hisouz" to "飞龙 - 飞翔斩",

        // ========== 经典格斗 - Misc ==========
        "wakuwaku7" to "Waku Waku 7 - 活力七战",
        "waku7" to "Waku Waku 7 - 活力七战",
        "wakuwak7" to "Waku Waku 7 - 活力七战",
        "wakuwak7a" to "Waku Waku 7 - 活力七战",
        "wakuwak7j" to "Waku Waku 7 - 活力七战 - 日版",
        "wakuseven" to "Waku Waku 7 - 活力七战",
        "aodk" to "Aggressors of Dark Kombat - 暗黑战斗者",
        "aodku" to "Aggressors of Dark Kombat - 暗黑战斗者 - 美版",
        "aodkj" to "Aggressors of Dark Kombat - 暗黑战斗者 - 日版",
        "aodke" to "Aggressors of Dark Kombat - 暗黑战斗者 - 欧版",
        "tws96" to "Twin Bee 双子精灵 96",
        "rbff2" to "真实恶狼传奇2",
        "breakers" to "Breakers - 破坏者",
        "breakers1" to "Breakers - 破坏者",
        "breakersj" to "Breakers - 破坏者 - 日版",
        "breakrev" to "Breakers Revenge - 破坏者复仇",
        "breakrev1" to "Breakers Revenge - 破坏者复仇",
        "breakrevj" to "Breakers Revenge - 破坏者复仇 - 日版",
        "breakrevh" to "Breakers Revenge - 破坏者复仇",
        "breakersa" to "Breakers - 破坏者",
        "breakrva" to "Breakers Revenge - 破坏者复仇",
        "fightfev" to "风云默示录",
        "fightfev1" to "风云默示录",
        "fightfeva" to "风云默示录",
        "fightfevj" to "风云默示录 - 日版",
        "fightfevk" to "风云默示录 - 韩版",
        "sasukou" to "风云默示录2 - 奥义乱舞",
        "sasukou1" to "风云默示录2 - 奥义乱舞",
        "sasukouj" to "风云默示录2 - 奥义乱舞 - 日版",
        "galaxyfg" to "Galaxy Fight - 银河之战",
        "galaxyfg2" to "Galaxy Fight2 - 银河之战2",
        "galaxfght" to "Galaxy Fight - 银河之战",
        "galaxfghtj" to "Galaxy Fight - 银河之战 - 日版",
        "wakuwak7a" to "Waku Waku 7 - 活力七战",
        "aodk" to "Aggressors of Dark Kombat - 暗黑战斗者",
        "kabukikl" to "歌舞伎 - 街机格斗",
        "kabukiklj" to "歌舞伎 - 街机格斗 - 日版",
        "kabukikll" to "歌舞伎 - 街机格斗 - 改版",
        "ninjam" to "忍者大师 - 街机格斗",
        "ninjamas" to "忍者大师 - 街机格斗",
        "ninjamasj" to "忍者大师 - 街机格斗 - 日版",
        "bjourney" to "战国传承3 - 武者之旅",
        "sengoku3" to "战国传承3",
        "sengoku3h" to "战国传承3",
        "sengoku3u" to "战国传承3 - 美版",
        "sengoku3j" to "战国传承3 - 日版",

        // ========== Sports / Racing - Misc ==========
        "polepos" to "Pole Position - 极速赛车",
        "polepos1" to "Pole Position - 极速赛车",
        "poleposj" to "Pole Position - 极速赛车 - 日版",
        "polepos2" to "Pole Position II - 极速赛车2",
        "polepos2a" to "Pole Position II - 极速赛车2",
        "polepos2j" to "Pole Position II - 极速赛车2 - 日版",
        "pacmanh" to "吃豆人 - 改版H",
        "pacman" to "吃豆人",
        "pacman1" to "吃豆人",
        "pacmanm" to "吃豆人 - 改版M",

        // ========== 经典街机射击 Misc ==========
        "cosmo" to "Cosmopolis - 宇宙警察",
        "cosmo1" to "Cosmopolis - 宇宙警察",
        "cavenger" to "Captain Cavenger - 船长搜救",
        "gunboat" to "Gunboat - 炮艇",
        "gunboatu" to "Gunboat - 炮艇 - 美版",
        "gunboatj" to "Gunboat - 炮艇 - 日版",
        "lockload" to "Lock 'n' Load - 装弹上膛",
        "lockload1" to "Lock 'n' Load - 装弹上膛",
        "lockloadj" to "Lock 'n' Load - 装弹上膛 - 日版",
        "cannon" to "Cannon Dancer - 魔剑神兵",
        "cannon1" to "Cannon Dancer - 魔剑神兵",
        "cannonj" to "Cannon Dancer - 魔剑神兵 - 日版",
        "cannonu" to "Cannon Dancer - 魔剑神兵 - 美版",
        "osman" to "Cannon Dancer - 魔剑神兵 - 美版",
        "strider" to "Strider - 飞龙卫士",
        "strider2" to "Strider 2 - 飞龙卫士2",
        "strider2u" to "Strider 2 - 飞龙卫士2 - 美版",
        "strider2j" to "Strider 2 - 飞龙卫士2 - 日版",
        "striderh" to "Strider - 飞龙卫士 - 改版",
        "strideru" to "Strider - 飞龙卫士 - 美版",
        "striderj" to "Strider - 飞龙卫士 - 日版",

        // ========== KOF 改版 / 民间魔改 ==========
        "kof97pls" to "拳皇97 Plus",
        "kof97ori" to "拳皇97 - 原版",
        "kof97b" to "拳皇97 - 改版",
        "kof97o" to "拳皇97 - 原版",
        "kof97x" to "拳皇97 - 魔改版",
        "kof97m" to "拳皇97 - 改版M",
        "kof97k" to "拳皇97 - 韩版",
        "kof97sp" to "拳皇97 - 特殊版",
        "kof97sp1" to "拳皇97 - 特殊版1",
        "kof97sp2" to "拳皇97 - 特殊版2",
        "kof97c" to "拳皇97 - 中文版",
        "kof97ch" to "拳皇97 - 中文改版",
        "kof97ch1" to "拳皇97 - 中文改版1",
        "kof97ch2" to "拳皇97 - 中文改版2",
        "kof97t" to "拳皇97 - 测试版",
        "kof97ta" to "拳皇97 - 测试版",
        "kof97tb" to "拳皇97 - 测试版",
        "kof97tc" to "拳皇97 - 测试版",
        "kof97td" to "拳皇97 - 测试版",
        "kof97te" to "拳皇97 - 测试版",
        "kof97tf" to "拳皇97 - 测试版",
        "kof97tg" to "拳皇97 - 测试版",
        "kof97th" to "拳皇97 - 测试版",
        "kof97ti" to "拳皇97 - 测试版",
        "kof97tj" to "拳皇97 - 测试版",
        "kof97tk" to "拳皇97 - 测试版",
        "kof97tl" to "拳皇97 - 测试版",
        "kof97tm" to "拳皇97 - 测试版",
        "kof97tn" to "拳皇97 - 测试版",
        "kof97to" to "拳皇97 - 测试版",
        "kof97tp" to "拳皇97 - 测试版",
        "kof97tq" to "拳皇97 - 测试版",
        "kof97tr" to "拳皇97 - 测试版",
        "kof97ts" to "拳皇97 - 测试版",
        "kof97tt" to "拳皇97 - 测试版",
        "kof97tu" to "拳皇97 - 测试版",
        "kof97tv" to "拳皇97 - 测试版",
        "kof97tw" to "拳皇97 - 测试版",
        "kof97tx" to "拳皇97 - 测试版",
        "kof97ty" to "拳皇97 - 测试版",
        "kof97tz" to "拳皇97 - 测试版",

        // ========== KOF 后续版本民间版 ==========
        "kof98pls" to "拳皇98 Plus",
        "kof98ori" to "拳皇98 - 原版",
        "kof98b" to "拳皇98 - 改版",
        "kof98o" to "拳皇98 - 原版",
        "kof98x" to "拳皇98 - 魔改版",
        "kof98m" to "拳皇98 - 改版M",
        "kof98k" to "拳皇98 - 韩版",
        "kof98sp" to "拳皇98 - 特殊版",
        "kof98c" to "拳皇98 - 中文版",
        "kof98ch" to "拳皇98 - 中文改版",

        "kof2002um" to "拳皇2002 终极对决",
        "kof2002x" to "拳皇2002 - 魔改版",
        "kof2002m" to "拳皇2002 - 改版M",
        "kof2002pls" to "拳皇2002 Plus",

        // ========== 真人快打改版 ==========
        "umk3p" to "终极真人快打3 Plus",
        "umk3r" to "终极真人快打3 改版",
        "umk3l" to "终极真人快打3 - 改版L",
        "mk3p" to "真人快打3 Plus",
        "mk3l" to "真人快打3 - 改版L",
        "mkp" to "真人快打 Project",
        "mkp2" to "真人快打 Project 2",
        "mkp3" to "真人快打 Project 3",

        // ========== 杂项常见 ==========
        "jojoba" to "JoJo的奇妙冒险 - 未来遗产",
        "jojobane" to "JoJo的奇妙冒险 - 未来遗产",
        "jojobanj" to "JoJo的奇妙冒险 - 未来遗产",
        "jojobanr" to "JoJo的奇妙冒险 - 未来遗产 - 改版",

        // ========== 早期格斗 ==========
        "yiear" to "Yie Ar Kung-Fu - 一二三功夫",
        "yiear1" to "Yie Ar Kung-Fu - 一二三功夫",
        "yiear2" to "Yie Ar Kung-Fu2 - 一二三功夫2",
        "yiearj" to "Yie Ar Kung-Fu - 一二三功夫 - 日版",
        "kungfu" to "Kung-Fu - 功夫",
        "kungfu1" to "Kung-Fu - 功夫",
        "kungfuj" to "Kung-Fu - 功夫 - 日版",
        "spartanx" to "Spartan X - 斯巴达克斯",
        "spartanxj" to "Spartan X - 斯巴达克斯 - 日版",
        "spartanx2" to "Spartan X2 - 斯巴达克斯2",

        // ========== 经典赛车 Misc ==========
        "rachero" to "Racing Hero - 赛车英雄",
        "rachero1" to "Racing Hero - 赛车英雄",
        "racheroj" to "Racing Hero - 赛车英雄 - 日版",
        "pdrift" to "Power Drift - 极速飞车",
        "pdrift1" to "Power Drift - 极速飞车",
        "pdriftj" to "Power Drift - 极速飞车 - 日版",
        "outrunb" to "OutRun - 改版",
        "vr" to "Virtua Racing - VR赛车",
        "vr1" to "Virtua Racing - VR赛车",
        "vru" to "Virtua Racing - VR赛车 - 美版",
        "vrj" to "Virtua Racing - VR赛车 - 日版",
        "vre" to "Virtua Racing - VR赛车 - 欧版",
        "vrl" to "Virtua Racing - VR赛车 - 改版L",
        "vrh" to "Virtua Racing - VR赛车 - 改版H",
        "daytona" to "Daytona USA - 蒙特卡罗拉力赛",
        "daytona1" to "Daytona USA - 蒙特卡罗拉力赛",
        "daytonau" to "Daytona USA - 蒙特卡罗拉力赛 - 美版",
        "daytonaj" to "Daytona USA - 蒙特卡罗拉力赛 - 日版",
        "daytone" to "Daytona USA - 蒙特卡罗拉力赛 - 欧版",
        "daytona2" to "Daytona USA 2 - 蒙特卡罗拉力赛2",
        "daytona2u" to "Daytona USA 2 - 蒙特卡罗拉力赛2 - 美版",
        "daytona2j" to "Daytona USA 2 - 蒙特卡罗拉力赛2 - 日版",

        // ========== CPS2 经典 Puzzles ==========
        "puzzloop" to "Puzzle Loop - 神奇泡泡",
        "puzzloop2" to "Puzzle Loop2 - 神奇泡泡2",
        "puzzloop2a" to "Puzzle Loop2 - 神奇泡泡2",
        "puzzloop2j" to "Puzzle Loop2 - 神奇泡泡2 - 日版",
        "puzzloop2u" to "Puzzle Loop2 - 神奇泡泡2 - 美版",
        "pzloop2" to "Puzzle Loop2 - 神奇泡泡2",
        "pzloop2j" to "Puzzle Loop2 - 神奇泡泡2 - 日版",
        "pzloop2u" to "Puzzle Loop2 - 神奇泡泡2 - 美版",

        // ========== Sega Classic Misc ==========
        "ttrx" to "Tetris - 俄罗斯方块 (Sega)",
        "ttrx1" to "Tetris - 俄罗斯方块 (Sega)",
        "ttrxj" to "Tetris - 俄罗斯方块 (Sega) - 日版",
        "col3" to "Columns III - 宝石方块3",
        "columns" to "Columns - 宝石方块",
        "columns1" to "Columns - 宝石方块",
        "columns2" to "Columns II - 宝石方块2",
        "columns3" to "Columns III - 宝石方块3",
        "columnsj" to "Columns - 宝石方块 - 日版",
        "baku" to "Baku Baku - 爆爆动物",
        "baku1" to "Baku Baku - 爆爆动物",
        "bakuj" to "Baku Baku - 爆爆动物 - 日版",
        "puyopuyo" to "Puyo Puyo - 魔法气泡",
        "puyopuyo1" to "Puyo Puyo - 魔法气泡",
        "puyopuyoj" to "Puyo Puyo - 魔法气泡 - 日版",
        "puyopuyo2" to "Puyo Puyo2 - 魔法气泡2",
        "puyopuyo2j" to "Puyo Puyo2 - 魔法气泡2 - 日版",
        "puyosun" to "Puyo Puyo Sun - 魔法气泡 Sun",
        "puyosunj" to "Puyo Puyo Sun - 魔法气泡 Sun - 日版",
        "puyoda" to "Puyo Puyo Da! - 魔法气泡 Da!",
        "puyodaj" to "Puyo Puyo Da! - 魔法气泡 Da! - 日版",
        "puyo" to "Puyo Puyo - 魔法气泡",

        // ========== NeoGeo 射击 Misc ==========
        "viewpnt" to "Viewpoint - 视点",
        "viewpntj" to "Viewpoint - 视点 - 日版",
        "zedblad" to "Zed Blade - 雷霆战机",
        "zedblade" to "Zed Blade - 雷霆战机",
        "zedbladej" to "Zed Blade - 雷霆战机 - 日版",
        "blazstar" to "Blazing Star - 烈火战机",
        "blazstarj" to "Blazing Star - 烈火战机 - 日版",
        "blazstr" to "Blazing Star - 烈火战机",
        "blazstrj" to "Blazing Star - 烈火战机 - 日版",
        "preisle" to "Prehistoric Isle - 史前岛",
        "preisle2" to "Prehistoric Isle 2 - 史前岛2",
        "preislej" to "Prehistoric Isle - 史前岛 - 日版",
        "preisleu" to "Prehistoric Isle - 史前岛 - 美版",
        "psoldier" to "Pulstar - 战机",
        "psoldierj" to "Pulstar - 战机 - 日版",
        "lasthope" to "Last Hope - 最后希望",
        "lasthopej" to "Last Hope - 最后希望 - 日版",
        "stfin" to "Strike Force - 战斗小队",
        "stfin1" to "Strike Force - 战斗小队",
        "stfinj" to "Strike Force - 战斗小队 - 日版"
    )

    /**
     * 已知的版本后缀 → 友好提示（用于未在主表中找到的驱动名）。
     *
     * 例如 kof98h.zip 中的 "h" 代表 "Hack" 修订版，
     * 我们尝试先去掉后缀再查表。
     */
    private val REVISION_SUFFIXES = listOf(
        "h" to " - 改版",
        "u" to " - 美版",
        "j" to " - 日版",
        "e" to " - 欧版",
        "a" to " - 亚洲版",
        "k" to " - 韩版",
        "p" to " - Plus",
        "r1" to " - 改版1",
        "r2" to " - 改版2",
        "r3" to " - 改版3",
        "b" to " - 改版",
        "o" to " - 原版",
        "bl" to " - Bootleg/魔改",
        "t" to " - 测试版",
        "c" to " - 中文版",
        "ch" to " - 中文改版",
        "sp" to " - 特殊版",
        "m" to " - 修正版",
        "x" to " - 魔改版",
        "s" to " - Super"
    )

    /**
     * 根据驱动名查找游戏中文名。
     *
     * 查找策略：
     *   1) 精确匹配（不区分大小写）
     *   2) 去除常见后缀（h/u/j/e/a/k/p/r1/r2/b/o/bl/t/c/ch/sp/m/x）后再匹配
     *   3) 仍找不到 → 返回 null（调用方使用原驱动名）
     *
     * @param driverName zip 文件名（不含 .zip 后缀），如 "kof98h" / "mvc"
     * @return 中文名称，如 "拳皇98 - 梦之终结未圆满"；找不到返回 null
     */
    fun lookup(driverName: String?): String? {
        if (driverName.isNullOrBlank()) return null
        val key = driverName.trim().lowercase()

        // 1) 精确匹配
        DRIVER_TO_CN[key]?.let { return it }

        // 2) 去除版本后缀再匹配
        //    例如 "kof98h" → 去掉 "h" → "kof98" → "拳皇98 - ..."
        for ((suffix, label) in REVISION_SUFFIXES) {
            if (key.endsWith(suffix) && key.length > suffix.length + 2) {
                val base = key.removeSuffix(suffix)
                DRIVER_TO_CN[base]?.let { cn ->
                    // 如果主表里已经有带后缀的精确条目，会优先返回（已处理）
                    // 这里仅追加修饰
                    return if (cn.contains(" - ")) "$cn ($label)" else "$cn$label"
                }
            }
        }

        // 3) 尝试去掉末尾的数字（"mvc2" → "mvc"），再查一次
        val strippedTrailingDigit = key.replace(Regex("\\d+$"), "")
        if (strippedTrailingDigit.length >= 2 && strippedTrailingDigit != key) {
            DRIVER_TO_CN[strippedTrailingDigit]?.let { return it }
        }

        return null
    }

    /**
     * 解析完整的 zip 文件名（含扩展名）→ 中文名。
     * 兼容 .zip / .7z / 大写扩展名。
     *
     * @param fileName 例如 "kof98h.zip"、"Mvc.7z"、"UNKNOWN_FILE.ZIP"
     * @return 中文名，找不到时返回 null（调用方应回退到 fileName 去扩展名）
     */
    fun lookupByFileName(fileName: String?): String? {
        if (fileName.isNullOrBlank()) return null
        val lower = fileName.lowercase()
        val driverName = when {
            lower.endsWith(".zip") -> fileName.removeSuffix(".zip").removeSuffix(".ZIP")
            lower.endsWith(".7z") -> fileName.removeSuffix(".7z").removeSuffix(".7Z")
            else -> fileName.substringBeforeLast('.', fileName)
        }
        return lookup(driverName)
    }

    /**
     * 给定原始文件名，返回最适合显示的标题：
     *   - 优先使用中文名
     *   - 找不到则使用驱动名（去扩展名）
     *
     * 用于 RomStore.add 入口的便捷包装。
     */
    fun resolveDisplayTitle(fileName: String?): String {
        return lookupByFileName(fileName) ?: fileName?.substringBeforeLast('.') ?: "未知游戏"
    }
}
